# Generated by Django 5.1.6 on 2025-02-22 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffnsn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=10)),
                ('door_number', models.TextField()),
                ('apartment_name', models.CharField(blank=True, max_length=35, null=True)),
                ('street_name', models.CharField(max_length=35)),
                ('taluk', models.CharField(max_length=35)),
                ('block', models.CharField(max_length=35)),
                ('district', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('pincode', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffPersonalInformation',
            fields=[
                ('staff_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('designation', models.PositiveSmallIntegerField(choices=[(0, 'Professor'), (1, 'Associate Professor'), (2, 'Assistant Professor')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('religion', models.CharField(max_length=50)),
                ('community', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('staff_mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhar_number', models.BigIntegerField(unique=True)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('father_mobile', models.BigIntegerField()),
                ('mother_mobile', models.BigIntegerField()),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('communication_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_address', to='staffnsn.staffaddress')),
                ('permanent_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='staffnsn.staffaddress')),
            ],
        ),
    ]
